# Generated by Django 4.1.5 on 2023-01-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='next_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='next_step_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='New Todo Item', max_length=200),
        ),
    ]
